# from collections import Counter
# mark =Counter['23','34','56','45','67']
# for i in mark.elements(mark):
#     print(i,end="")

# from collections import Counter

# list=Counter("jhsdhjh")
# for i in list.elements():
#     print(i,end="")
# # c = Counter('ABCABC')
# sorted(c.elements())
# ['A', 'A', 'B', 'B', 'C', 'C']
# 
# 
# import calendar

# yy=2020,2021,2022
# mm=10,11,12
# print(calendar.month(yy,mm))
# s = self.formatmonthname(theyear, themonth, 7 * (w + 1) - 1)
# s = month_name[themonth]
# funcs = self._months[i]

# import calendar

# print("2018 year of this calendar")
# print(calendar.calendar(2023))